# Generated by Django 3.2 on 2022-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1500)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
