# Generated by Django 3.2 on 2021-12-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicineName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1500)),
                ('level', models.JSONField(blank=True, default=list, null=True)),
                ('count', models.CharField(default=None, max_length=100, null=True)),
                ('badInfluence', models.CharField(default=None, max_length=1000, null=True)),
                ('foodOrNot', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
