# Generated by Django 3.2 on 2021-11-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('userType', models.CharField(default=None, max_length=40, null=True)),
                ('parentId', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
