# Generated by Django 3.2.9 on 2022-01-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1500)),
            ],
        ),
    ]
