# Generated by Django 3.2 on 2022-05-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('levelNumber', models.IntegerField()),
                ('stepNumber', models.IntegerField()),
                ('description', models.CharField(max_length=1500)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('requirements', models.CharField(default=None, max_length=1500, null=True)),
                ('isDone', models.BooleanField(default=False)),
                ('isCurrStep', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('mail', 'levelNumber', 'stepNumber')},
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelNumber', models.IntegerField()),
                ('stepNumber', models.IntegerField()),
                ('description', models.CharField(max_length=1500)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('requirements', models.CharField(default=None, max_length=1500, null=True)),
            ],
            options={
                'unique_together': {('levelNumber', 'stepNumber')},
            },
        ),
    ]
