# Generated by Django 3.2 on 2022-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicineName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1500)),
                ('levels', models.JSONField(blank=True, default=list, null=True)),
                ('count', models.CharField(default=None, max_length=100, null=True)),
                ('badInfluence', models.JSONField(blank=True, default=list, null=True)),
                ('foodOrNot', models.CharField(default=None, max_length=100, null=True)),
                ('days', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('medicineName', models.CharField(max_length=100)),
                ('count', models.CharField(default=None, max_length=100, null=True)),
                ('days', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'unique_together': {('mail', 'medicineName')},
            },
        ),
    ]
