# Generated by Django 3.2 on 2022-03-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('videoDescription', models.CharField(max_length=1500)),
                ('videoUrl', models.URLField()),
            ],
        ),
    ]
